# Default values for korrel8r

nameOverride: ""
fullnameOverride: ""

# Global configuration
global:
  namespace: openshift-cluster-observability-operator

# Patch flag: when true, apply ConfigMap/Deployment/Route
patch:
  enabled: false

# Korrel8r configuration
korrel8r:
  name: korrel8r-patch
  stores:
    log:
      lokiStackUrl: https://logging-loki-gateway-http.openshift-logging.svc:8080
    netflow:
      lokiStackUrl: https://loki-gateway-http.netobserv.svc:8080
    trace:
      tempoStackUrl: https://tempo-tempostack-gateway.observability-hub.svc.cluster.local:8080/api/traces/v1/platform/tempo/api/search

# Container image
image:
  repository: quay.io/korrel8r/korrel8r
  tag: "0.8.3"
  pullPolicy: Always

# ServiceAccount settings
serviceAccount:
  create: false
  name: troubleshooting-panel-sa

# Route configuration
route:
  enabled: false
  tls:
    termination: reencrypt

# Additional labels and annotations
commonLabels: {}
commonAnnotations: {}

