{{- $namespace := include "korrel8r.namespace" . }}
{{- $existingRoute := lookup "route.openshift.io/v1" "Route" $namespace .Values.korrel8r.name }}
{{- if not $existingRoute }}
# Korrel8r Route - Skipped if already exists in namespace
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.korrel8r.name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "korrel8r.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ .Values.korrel8r.name }}
  tls:
    termination: {{ .Values.route.tls.termination }}
{{- end }}

