{{- if .Values.minio.service.enabled }}
{{- $namespace := include "minio.namespace" . }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "minio.fullname" . }}-api
  namespace: {{ $namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "minio.fullname" . }}
    weight: 100
  port:
    targetPort: api
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "minio.fullname" . }}-webui
  namespace: {{ $namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "minio.fullname" . }}
    weight: 100
  port:
    targetPort: console
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
