{{- if .Values.patch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.korrel8r.name }}
  namespace: {{ include "korrel8r.namespace" . }}
  labels:
    {{- include "korrel8r.labels" . | nindent 4 }}
    app.kubernetes.io/instance: korrel8r
    app.kubernetes.io/managed-by: observability-operator
    app.kubernetes.io/part-of: UIPlugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: korrel8r
      app.kubernetes.io/managed-by: observability-operator
      app.kubernetes.io/part-of: UIPlugin
  template:
    metadata:
      name: {{ .Values.korrel8r.name }}
      namespace: {{ include "korrel8r.namespace" . }}
      labels:
        app.kubernetes.io/name: {{ include "korrel8r.name" . }}
        app.kubernetes.io/instance: korrel8r
        app.kubernetes.io/managed-by: observability-operator
        app.kubernetes.io/part-of: UIPlugin
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: korrel8r
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - korrel8r
        - web
        - --https=:9443
        - --cert=/secrets/tls.crt
        - --key=/secrets/tls.key
        - --config=/config/korrel8r.yaml
        ports:
        - containerPort: 9443
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: serving-cert
          mountPath: /secrets/
          readOnly: true
        - name: korrel8r-config
          mountPath: /config/
          readOnly: true
      volumes:
      - name: serving-cert
        secret:
          secretName: korrel8r
          defaultMode: 420
      - name: korrel8r-config
        configMap:
          name: {{ .Values.korrel8r.name }}
          defaultMode: 420
{{- end }}

