apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: troubleshooting-panel
  namespace: {{ include "korrel8r.namespace" . }}
  labels:
    {{- include "korrel8r.labels" . | nindent 4 }}
spec:
  type: TroubleshootingPanel

