# Use the 'create api' subcommand to add watches to this file.
- group: aiobs.rh-ai-quickstart.io
  version: v1alpha1
  kind: AIObservabilitySummarizer
  chart: helm-charts/aiobs-stack
#+kubebuilder:scaffold:watch

