apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.trustedCA.configMapName | default "mcp-server-trusted-ca-bundle" }}
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
data:
  service-ca.crt: ""


