apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "mcp-server-svc" }}
  {{- if and .Values.tls.enabled .Values.tls.serviceCertAnnotation }}
  annotations:
    {{ .Values.tls.serviceCertAnnotation }}: {{ .Values.tls.secretName }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deployment.name | default "mcp-server" }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}


