{{- $namespace := include "otel-collector.namespace" . }}
{{- $saName := include "otel-collector.serviceAccountName" . }}
{{- $existingSA := lookup "v1" "ServiceAccount" $namespace $saName }}
{{- if and .Values.serviceAccount.create (not $existingSA) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}